blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed
app_name = 'blog'

urlpatterns = [
    # path("",views.PostListView.as_view(),name="post_list"),
    path("",views.post_list,name="post_list"),
    path("tag/<slug:tag_slug>/",views.post_list,name="post_list"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/",views.post_detail,name="post_detail"),
    path("<int:post_id>/share/",views.post_share,name="post_share"),
    path("feed/",LatestPostFeed(),name="post_feed"),
    path("search/",views.post_search,name="post_search"),
    ]

weblog/urls.py
from django.contrib import admin, sitemaps
from django.urls import path , include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from datetime import time
from django.db import models
from django.db.models import manager
from django.db.models.deletion import CASCADE
from django.db.models.fields import BooleanField, CharField, EmailField
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS = (
        ("draft",'Draft'),
        ("published",'Published')
    )
    author = ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    title = models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS,default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse("blog:post_detail",args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

    def __str__(self):
        return self.title

    # class Meta:
    #     ordering = ('publish',)

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=CASCADE,related_name="comments")
    name = models.CharField(_("نام"), max_length=50)
    email = models.EmailField(max_length=254)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(widget=forms.Textarea,required=False)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')


class SearchForm(forms.Form):
    query = forms.CharField() 

blog/views.py
from django import forms
from django.contrib.postgres import search
from django.core import paginator
from django.db.models import query
from django.db.models.fields import AutoField
from django.db.models.query_utils import PathInfo
from django.shortcuts import render , get_object_or_404
from .models import Post , Comment
from .models import Post , Comment 
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm , CommentForm
from .forms import EmailPostForm , CommentForm, SearchForm
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector ,SearchQuery ,SearchRank
# Create your views here.


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 4
#     template_name = "blog/post/list.html"


def post_list(request,tag_slug=None):
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts , 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {"posts":posts , 'page':page , "tag":tag}
    return render(request,'blog/post/list.html',context)



#/2021/3/20/second-blog
def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,status="published",publish__year=year,publish__month=month,publish__day=day)
    comments = post.comments.filter(active=True)

    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags = Count('tags')).order_by('-same_tags', '-publish')

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()
    context = {'post':post,'form':comment_form ,'comments':comments, 's_posts':similar_posts}
    return render(request,'blog/post/detail.html',context)

def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status="published")
    if request.method =='POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommended yor"
            message = f"{post.title} in {post_url} and {cd['comment']}"
            send_mail(
                subject,message,"weblog.ir@gmail.com",
                [cd['to']]
            )



    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form})


#search view
def post_search(request):
    form = SearchForm()
    query = None
    resault = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # A B C D => 1.0 , 0.4 , 0.2 , 0.1 
            search_vector = SearchVector('title', weight='A') + (SearchVector('body', weight='C'))
            search_query = SearchQuery(query)
            resault = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector,search_query)).filter(rank__gte=0.5).order_by('-rank')  
    return render(request, 'blog/post/search.html',{'form':form,'query':query,'resaults':resault}) 

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% block content %}

    {% endblock content %}
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/post/detail.html
{% extends 'blog/base.html'%}
{% load blog_tags %}

{% block content %}
<h1>{{post.title}}</h1>
<h6>author:{{post.author}} at {{post.created}}</h6>
<hr>
<p>{{post.body}}</p>
<div class="mb-3 col-6">
    <form method="POST">
    {% csrf_token %}
    {% for field in form %}
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
        <br>
    {% endfor %}
        <!-- {{form.as_p}} -->
    <input type="submit" value="Set Comment">
    </form>
    {% with comments.count as total_comments %}
    <h5>number of comments : {{total_comments}}</h5>
{% endwith %}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share</a>
    </p>
    <div class=col-6>
        {% for cm in comments %}
            {{cm.name}} is written: {{cm.body}}
            <hr>
            <br/>
        {% endfor %}

        <div class="row my_3">
<h3>Similar Posts</h3>
<div class="col">
    {% for post in s_posts %}
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    <hr/>
    {% endfor %}
</div>
        </div>
    </div>
    <p>Tags: 
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list' tag.slug %}">{{tag.name}}</a> -
        {% endfor %}
    </p>
{% endblock content %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
      <li>
          <a href="{{post.get_absolute_url}}">{{post.title}}</a>
      </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends 'blog/base.html'%}
{% load blog_tags %}
{% block content %}


<h3>we have {% total_posts %} published posts</h3>
<h3>Latest Posts:</h3>
{% show_latest_posts 3 %}

{% if tag %}
<h3>posts with tag {{tag}}</h3>
{% else %}
<h3>list of posts</h3>
{% endif %}
<ul>
    {% for post in posts %}
    <div class="list-group">
    <a href="{{post.get_absolute_url}}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{post.title}}</h5>
          <small class="text-muted">{{post.created}}</small>
        </div>
        <p class="mb-1">{{post.author}}</p>
        <small class="text-muted">{{post.body|slice:":30"}} . . . </small>
      </a>
    </div>
    {% endfor %}
</ul>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
        {% if posts.has_previous %}
      <a class="page-link" href="?page={{posts.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      <a class="page-link" href="?page=1" aria-label="Previous">
        <span aria-hidden="true">first</span>
          {% endif %}
      </a>
    </li>
    {% for page in posts.paginator.page_range %}
    <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    {% endfor %}
    <li class="page-item">

      {% if posts.has_next %}
      <a class="page-link" href="?page={{posts.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      <a class="page-link" href="?page={{posts.paginator.num_pages}}" aria-label="Next">
        <span aria-hidden="true">Last</span>
        {% endif %}
      </a>
    </li>
  </ul>
</nav>
<p><a href="{% url 'blog:post_feed' %}"> Subscribe in RSS</a></p>


{% endblock content %}

templates/blog/post/search.html
{% extends 'blog/base.html'%}

{% block content %}
{% if query %}
<h1>
    Posts contains {{query}}
</h1>
<h3>
    {% with resaults.count as total_resaults %}
      Found {{total_resaults}} resault
      {% endwith %}
</h3>
{% for resault in resaults %}
<h3>
    <a href="{{resault.get_absolute_url}}">{{resault.title}}</a></h3>
    <p>{{resault.body|slice:":30"}}</p>

{% endfor %}
{% endif %}
<h1>Search Form</h1>
<form action="" method="GET">
    {{form.as_p}}
    <input type="submit" value="search">
</form>
{% endblock content %} 

templates/blog/post/share.html
{% extends 'blog/base.html'%}
{% block content %}
<form method="POST">
{% csrf_token %}
{% for field in form %}
  {{field.errors}}
  {{field.label_tag}}
  {{field}}
  <br>
{% endfor %}
    <!-- {{form.as_p}} -->
<input type="submit" value="send email">
</form>
{% endblock content %}